document:
  name: Linee Guida sull'interoperabilità tecnica

  description:
      Linee Guida sull'interoperabilità tecnica delle Pubbliche Amministrazioni
  tags:
    - interoperabilità
    - API
    - linee guida